# Generated by CoffeeScript 1.4.0

window.calendar_url = 'http://events.cornell.edu'

# define slzr/reports/average_time_to_approval module
modulejs.define 'slzr/reports/average_time_to_approval', ['jquery', 'underscore'], ($, _) ->

  # initialize events created by day
  averageTimesToApproval = null

  # define method to get average time to approval
  getAverageTimesToApproval: ->
    dateRange = $('#date_range_select').val()
    endDate = new Date
    startDate = new Date

    # set start date and end date for reporting
    startDate.setDate startDate.getDate() - parseInt(dateRange) + 1

    # build the type params like &type[]=1&type[]=2
    if $("#filter-event_types").val() == ""
      type_params = ""
    else
      type_params = '&type[]=' + $("#filter-event_types").val()

    $.ajax
      url: window.calendar_url + '/api/2/events/stats/approval_time'
      type: 'GET'
      data: 'start=' + startDate.toISOString().slice(0, 10) + '&end=' + endDate.toISOString().slice(0, 10) + type_params
      cache: false
      async: false
      dataType: 'json'
      success: (data, textStatus, jqXHR) ->
        averageTimesToApproval = data

  # method to show report
  showDataOnReport: ->
    reportBody = ''

    reportBody += '<tr>'
    reportBody += '<td>' + $("#filter-event_types option:selected").text() + '</td>'
    hours = Math.floor( averageTimesToApproval.average_time / 3600 )
    seconds = averageTimesToApproval.average_time % 3600 % 60
    minutes = Math.floor( (averageTimesToApproval.average_time % 3600) / 60 )
    reportBody += '<td>' + hours + "h " + minutes + "m " + seconds + "s" + '</td>'
    reportBody += '</tr>'

    $('.item-list tbody').html reportBody

Slzr.jQuery ($) ->

  return unless $(document.body).is('.admin-analytics-average-time-to-approval')

  $('#custom_date_range').hide()

  AverageTimeModule = modulejs.require('slzr/reports/average_time_to_approval')
  AverageTimeModule.getAverageTimesToApproval()
  AverageTimeModule.showDataOnReport()

  # action triggered when clicking 'update' button
  $(document).onAction 'update-report', (event) ->
    if $("#date_range_select").val() == "Custom" && ($("#start_date_input").data("date-status") != "ok" && $("#end_date_input").data("date-status") != "ok")
      # show notice
    else
      AverageTimeModule.getAverageTimesToApproval()
      AverageTimeModule.showDataOnReport()
