# Generated by CoffeeScript 1.4.0

window.calendar_url = 'http://events.cornell.edu'

# define slzr/reports/events_created_by_day module
modulejs.define 'slzr/reports/events_created_by_day', ['jquery', 'underscore'], ($, _) ->

  # initialize the data for drawing chart
  eventsCreatedChart = null
  chartData =
    labels: []
    datasets: [ {
      label: 'Events Created By Day'
      fillColor: 'rgba(151,187,205,0.2)'
      strokeColor: 'rgba(151,187,205,1)'
      pointColor: 'rgba(151,187,205,1)'
      pointStrokeColor: '#fff'
      pointHighlightFill: '#fff'
      pointHighlightStroke: 'rgba(151,187,205,1)'
      data: []
    } ]

  chartDataForTotal =
    labels: []
    datasets: [ {
      label: 'Events Created By Day'
      fillColor: 'rgba(151,187,205,0.2)'
      strokeColor: 'rgba(151,187,205,1)'
      pointColor: 'rgba(151,187,205,1)'
      pointStrokeColor: '#fff'
      pointHighlightFill: '#fff'
      pointHighlightStroke: 'rgba(151,187,205,1)'
      data: []
    } ]

  # initialize events created by day
  eventsCreatedByDay = null

  # define method to get events created by day
  getEventsCreated: ->
    dateRange = $('#date_range_select').val()
    endDate = new Date
    startDate = new Date
    chartKind = 'daily'

    # set start date and end date for reporting
    if dateRange != 'Custom'
      startDate.setDate startDate.getDate() - parseInt(dateRange) + 1
    else
      startDate = $("#start_date_input").data("date")
      endDate = $("#end_date_input").data("date")

    daysDiff = (endDate.getTime() - startDate.getTime()) / (1000 * 3600 * 24)
    if daysDiff > 366
      $('#message-response-message').html('The date range must be 366 days or less.')
      $('#message-response').show()
      return false
    # check if showing chart daily or weekly
    if daysDiff >= 179
      chartKind = 'monthly'
    else if daysDiff > 14
      chartKind = 'weekly'


    # build the type params like &type[]=1&type[]=2
    type_params = ''
    $('input[name=\'type_id[]\']').each ->
      type_params += '&type[]=' + $(this).val()

    $.ajax
      url: window.calendar_url + '/api/2/events/stats/created'
      type: 'GET'
      data: 'start=' + startDate.toISOString().slice(0, 10) + '&end=' + endDate.toISOString().slice(0, 10) + type_params
      cache: false
      async: false
      dataType: 'json'
      success: (data, textStatus, jqXHR) ->
        eventsCreatedByDay = data

    chartData.datasets[0].data = []
    chartData.labels = []
    chartDataForTotal.datasets[0].data = []
    chartDataForTotal.labels = []

    if eventsCreatedByDay != null
      durationStartDate = ""
      totalCountByDuration = 0
      totalCount = 0
      $(eventsCreatedByDay.created).each (index, element) ->
        totalCount += element.count
        if chartKind == 'daily'
          # set events created chart data
          chartData.datasets[0].data.push element.count
          chartData.labels.push moment(element.date, "YYYY-MM-DD[T]hh:mm:ss").format("MMM DD, YYYY")

          # set events total count chart data
          chartDataForTotal.datasets[0].data.push totalCount
          chartDataForTotal.labels.push moment(element.date, "YYYY-MM-DD[T]hh:mm:ss").format("MMM DD, YYYY")
        else if chartKind == 'weekly'
          if index % 7 == 0
            durationStartDate = moment(element.date, "YYYY-MM-DD[T]hh:mm:ss").format("MMM DD, YYYY")
          if index % 7 == 6 || index == eventsCreatedByDay.created.length - 1
            # set events created chart data
            chartData.datasets[0].data.push totalCountByDuration += element.count
            totalCountByDuration = 0
            chartData.labels.push durationStartDate += " ~ " + moment(element.date, "YYYY-MM-DD[T]hh:mm:ss").format("MMM DD, YYYY")

            # set events total count chart data
            chartDataForTotal.datasets[0].data.push totalCount
            chartDataForTotal.labels.push durationStartDate += " ~ " + moment(element.date, "YYYY-MM-DD[T]hh:mm:ss").format("MMM DD, YYYY")

          totalCountByDuration += element.count
        else
          if index % 30 == 0
            durationStartDate = moment(element.date, "YYYY-MM-DD[T]hh:mm:ss").format("MMM DD, YYYY")
          if index % 30 == 29 || index == eventsCreatedByDay.created.length - 1
            # set events created chart data
            chartData.datasets[0].data.push totalCountByDuration += element.count
            totalCountByDuration = 0
            chartData.labels.push durationStartDate += " ~ " + moment(element.date, "YYYY-MM-DD[T]hh:mm:ss").format("MMM DD, YYYY")

            # set events total count chart data
            chartDataForTotal.datasets[0].data.push totalCount
            chartDataForTotal.labels.push durationStartDate += " ~ " + moment(element.date, "YYYY-MM-DD[T]hh:mm:ss").format("MMM DD, YYYY")

          totalCountByDuration += element.count
    return true
  # method to draw chart
  drawChart: ->
    if eventsCreatedChart != null
      eventsCreatedChart.destroy()
    ctx = document.getElementById('canvas').getContext('2d')

    if $('#show-events-created').is(':checked')
      eventsCreatedChart = new Chart(ctx).Line(chartData, responsive: true)
    else
      eventsCreatedChart = new Chart(ctx).Line(chartDataForTotal, responsive: true)

  # method to show report
  showDataOnReport: ->
    reportBody = ''
    $(eventsCreatedByDay.created).each (index, element) ->
      reportBody += '<tr>'
      reportBody += '<td>' + moment(element.date, "YYYY-MM-DD[T]hh:mm:ss").format("MMM DD, YYYY") + '</td>'
      reportBody += '<td>' + element.count + '</td>'
      reportBody += '</tr>'

    $('.item-list tbody').html reportBody

Slzr.jQuery ($) ->

  return unless $(document.body).is('.admin-analytics-events-created')

  EventsCreatedModule = modulejs.require('slzr/reports/events_created_by_day')
  EventsCreatedModule.getEventsCreated()
  EventsCreatedModule.drawChart()
  EventsCreatedModule.showDataOnReport()

  # action triggered when clicking 'update' button
  $(document).onAction 'update-report', (event) ->
    if $("#date_range_select").val() == "Custom" && ($("#start_date_input").data("date-status") != "ok" && $("#end_date_input").data("date-status") != "ok")
      # show notice
    else
      if EventsCreatedModule.getEventsCreated()
        EventsCreatedModule.drawChart()
        EventsCreatedModule.showDataOnReport()
