# Generated by CoffeeScript 1.4.0

window.calendar_url = 'http://events.cornell.edu'

# define slzr/reports/most_popular_events module
modulejs.define 'slzr/reports/most_popular_events', ['jquery', 'underscore'], ($, _) ->

  # initialize events created by day
  mostPopularEvents = null

  # define method to get most popular events
  getMostPopularEvents: ->
    dateRange = $('#date_range_select').val()
    endDate = new Date
    startDate = new Date

    # set start date and end date for reporting
    if dateRange != 'Custom'
      startDate.setDate startDate.getDate() - parseInt(dateRange) + 1
    else
      startDate = $("#start_date_input").data("date")
      endDate = $("#end_date_input").data("date")

    daysDiff = (endDate.getTime() - startDate.getTime()) / (1000 * 3600 * 24)
    if daysDiff > 366
      $('#message-response-message').html('The date range must be 366 days or less.')
      $('#message-response').show()
      return false

    $.ajax
      url: window.calendar_url + '/api/2/events'
      type: 'GET'
      data: 'sort=ranking&start=' + startDate.toISOString().slice(0, 10) + '&end=' + endDate.toISOString().slice(0, 10)
      cache: false
      async: false
      dataType: 'json'
      success: (data, textStatus, jqXHR) ->
        mostPopularEvents = data
        console.log(data)
    return true

  # method to show report
  showDataOnReport: ->
    reportBody = ''
    $(mostPopularEvents.events).each (index, element) ->
      reportBody += '<tr>'
      reportBody += '<td>' + moment(element.event.created_at, "YYYY-MM-DD[T]hh:mm:ss").format("MMM DD, YYYY") + '</td>'
      reportBody += '<td>' + element.event.title + '</td>'
      reportBody += '<td>' + moment(element.event.event_instances[0].event_instance.start, "YYYY-MM-DD[T]hh:mm:ss").format("MMM DD, YYYY") + '</td>'
      reportBody += '</tr>'

    $('.item-list tbody').html reportBody

Slzr.jQuery ($) ->

  return unless $(document.body).is('.admin-analytics-most-popular-events')

  $('#custom_date_range').hide()

  MostPopularEventsModule = modulejs.require('slzr/reports/most_popular_events')
  MostPopularEventsModule.getMostPopularEvents()
  MostPopularEventsModule.showDataOnReport()

  # action triggered when changing date range
  $('#date_range_select').change (event) ->
    if $(this).val() == 'Custom'
      $('#custom_date_range').show()
    else
      $('#custom_date_range').hide()

  # action triggered when clicking 'update' button
  $(document).onAction 'update-report', (event) ->
    if $("#date_range_select").val() == "Custom" && ($("#start_date_input").data("date-status") != "ok" && $("#end_date_input").data("date-status") != "ok")
      # show notice
    else
      if MostPopularEventsModule.getMostPopularEvents()
        MostPopularEventsModule.showDataOnReport()
