# Generated by CoffeeScript 1.4.0

window.calendar_url = 'http://events.cornell.edu'
window.event_id = '499347'

# define slzr/reports/page_views_on_single_event module
modulejs.define 'slzr/reports/page_views_on_single_event', ['jquery', 'underscore'], ($, _) ->

  # initialize the data for drawing chart
  pageViewsChart= null
  chartData =
    labels: []
    datasets: [ {
      label: 'Page Views On Single Event'
      fillColor: 'rgba(151,187,205,0.2)'
      strokeColor: 'rgba(151,187,205,1)'
      pointColor: 'rgba(151,187,205,1)'
      pointStrokeColor: '#fff'
      pointHighlightFill: '#fff'
      pointHighlightStroke: 'rgba(151,187,205,1)'
      data: []
    } ]

  # initialize page views on event data
  pageViewsOnEventData = null

  # define method to get page views on single event
  getPageViews: ->
    dateRange = $('#date_range_select').val()
    endDate = new Date
    startDate = new Date
    showChartWeekly = false

    # set start date and end date for reporting
    if dateRange != 'Custom'
      startDate.setDate startDate.getDate() - parseInt(dateRange) + 1
    else
      startDate = $("#start_date_input").data("date")
      endDate = $("#end_date_input").data("date")

    daysDiff = (endDate.getTime() - startDate.getTime()) / (1000 * 3600 * 24)
    if daysDiff > 366
      $('#message-response-message').html('The date range must be 366 days or less.')
      $('#message-response').show()
      return false

    # check if showing chart daily or weekly
    if daysDiff > 14
      showChartWeekly = true

    $.ajax
      url: window.calendar_url + '/api/2/events/' + window.event_id + '/stats/views'
      type: 'GET'
      data: 'start=' + startDate.toISOString().slice(0, 10) + '&end=' + endDate.toISOString().slice(0, 10)
      cache: false
      async: false
      dataType: 'json'
      success: (data, textStatus, jqXHR) ->
        pageViewsOnEventData = data

    chartData.datasets[0].data = []
    chartData.labels = []

    if pageViewsOnEventData != null
      weekStartDate = ""
      weekCount = 0
      $(pageViewsOnEventData.views).each (index, element) ->
        if showChartWeekly == false
          chartData.datasets[0].data.push element.count
          chartData.labels.push moment(element.date, "YYYY-MM-DD[T]hh:mm:ss").format("MMM DD, YYYY")
        else
          if index % 7 == 0
            weekStartDate = moment(element.date, "YYYY-MM-DD[T]hh:mm:ss").format("MMM DD, YYYY")
          if index % 7 == 6 || index == pageViewsOnEventData.views.length - 1
            chartData.datasets[0].data.push weekCount += element.count
            chartData.labels.push weekStartDate += " ~ " + moment(element.date, "YYYY-MM-DD[T]hh:mm:ss").format("MMM DD, YYYY")
          weekCount += element.count
    return true
  # method to draw chart with page views on single event
  drawChart: ->
    if pageViewsChart != null
      pageViewsChart.destroy()
    ctx = document.getElementById('canvas').getContext('2d')
    pageViewsChart = new Chart(ctx).Line(chartData, responsive: true)

  # method to show report with page views on single event
  showDataOnReport: ->
    reportBody = ''
    $(pageViewsOnEventData.views).each (index, element) ->
      reportBody += '<tr>'
      reportBody += '<td>' + moment(element.date, "YYYY-MM-DD[T]hh:mm:ss").format("MMM DD, YYYY") + '</td>'
      reportBody += '<td>' + element.count + '</td>'
      reportBody += '</tr>'

    $('.item-list tbody').html reportBody

Slzr.jQuery ($) ->

  return unless $(document.body).is('.admin-analytics-page-views-on-single-event')

  $('#custom_date_range').hide()

  PageViewsModule = modulejs.require('slzr/reports/page_views_on_single_event')
  PageViewsModule.getPageViews()
  PageViewsModule.drawChart()
  PageViewsModule.showDataOnReport()

  # action triggered when changing date range
  $(document).onAction 'change-date-range', (event) ->
    if $(this).val() == 'Custom'
      $('#custom_date_range').show()
    else
      $('#custom_date_range').hide()

  # action triggered when clicking 'update' button
  $(document).onAction 'update-report', (event) ->
    if $("#date_range_select").val() == "Custom" && ($("#start_date_input").data("date-status") != "ok" && $("#end_date_input").data("date-status") != "ok")
      # show notice
    else
      if PageViewsModule.getPageViews()
        PageViewsModule.drawChart()
        PageViewsModule.showDataOnReport()
