# Generated by CoffeeScript 1.4.0

window.calendar_url = 'http://events.cornell.edu'

# define slzr/reports/users_created_by_day module
modulejs.define 'slzr/reports/users_created_by_day', ['jquery', 'underscore'], ($, _) ->

  # initialize the data for drawing chart
  usersCreatedChart = null
  chartData =
    labels: []
    datasets: [ {
      label: 'Users Created By Day'
      fillColor: 'rgba(151,187,205,0.2)'
      strokeColor: 'rgba(151,187,205,1)'
      pointColor: 'rgba(151,187,205,1)'
      pointStrokeColor: '#fff'
      pointHighlightFill: '#fff'
      pointHighlightStroke: 'rgba(151,187,205,1)'
      data: []
    } ]

  # initialize users created by day
  usersCreatedByDay = null

  # define method to get users created by day
  getEventsCreated: ->
    dateRange = $('#date_range_select').val()
    endDate = new Date
    startDate = new Date
    chartKind = 'daily'

    # set start date and end date for reporting
    if dateRange != 'Custom'
      startDate.setDate startDate.getDate() - parseInt(dateRange) + 1
    else
      startDate = $("#start_date_input").data("date")
      endDate = $("#end_date_input").data("date")

    daysDiff = (endDate.getTime() - startDate.getTime()) / (1000 * 3600 * 24)
    if daysDiff > 366
      $('#message-response-message').html('The date range must be 366 days or less.')
      $('#message-response').show()
      return false

    # check if showing chart daily or weekly
    if daysDiff >= 179
      chartKind = 'monthly'
    else if daysDiff > 14
      chartKind = 'weekly'

    $.ajax
      url: window.calendar_url + '/api/2/users/stats/created'
      type: 'GET'
      data: 'start=' + startDate.toISOString().slice(0, 10) + '&end=' + endDate.toISOString().slice(0, 10)
      cache: false
      async: false
      dataType: 'json'
      success: (data, textStatus, jqXHR) ->
        usersCreatedByDay = data

    chartData.datasets[0].data = []
    chartData.labels = []

    if usersCreatedByDay != null
      weekStartDate = ""
      weekCount = 0
      $(usersCreatedByDay.created).each (index, element) ->
        if chartKind == 'daily'
          chartData.datasets[0].data.push element.count
          chartData.labels.push moment(element.date, "YYYY-MM-DD[T]hh:mm:ss").format("MMM DD, YYYY")
        else if chartKind == 'weekly'
          if index % 7 == 0
            weekStartDate = moment(element.date, "YYYY-MM-DD[T]hh:mm:ss").format("MMM DD, YYYY")
          if index % 7 == 6 || index == usersCreatedByDay.created.length - 1
            chartData.datasets[0].data.push weekCount += element.count
            chartData.labels.push weekStartDate += " ~ " + moment(element.date, "YYYY-MM-DD[T]hh:mm:ss").format("MMM DD, YYYY")
          weekCount += element.count
        else
          if index % 30 == 0
            weekStartDate = moment(element.date, "YYYY-MM-DD[T]hh:mm:ss").format("MMM DD, YYYY")
          if index % 30 == 29 || index == usersCreatedByDay.created.length - 1
            chartData.datasets[0].data.push weekCount += element.count
            chartData.labels.push weekStartDate += " ~ " + moment(element.date, "YYYY-MM-DD[T]hh:mm:ss").format("MMM DD, YYYY")
          weekCount += element.count
    return true

  # method to draw chart
  drawChart: ->
    if usersCreatedChart != null
      usersCreatedChart.destroy()
    ctx = document.getElementById('canvas').getContext('2d')
    usersCreatedChart = new Chart(ctx).Line(chartData, responsive: true)

  # method to show report
  showDataOnReport: ->
    reportBody = ''
    $(usersCreatedByDay.created).each (index, element) ->
      reportBody += '<tr>'
      reportBody += '<td>' + moment(element.date, "YYYY-MM-DD[T]hh:mm:ss").format("MMM DD, YYYY") + '</td>'
      reportBody += '<td>' + element.count + '</td>'
      reportBody += '</tr>'

    $('.item-list tbody').html reportBody

Slzr.jQuery ($) ->

  return unless $(document.body).is('.admin-analytics-users-created')

  $('#custom_date_range').hide()

  UsersCreatedModule = modulejs.require('slzr/reports/users_created_by_day')
  UsersCreatedModule.getEventsCreated()
  UsersCreatedModule.drawChart()
  UsersCreatedModule.showDataOnReport()

  # action triggered when changing date range
  $('#date_range_select').change (event) ->
    if $(this).val() == 'Custom'
      $('#custom_date_range').show()
    else
      $('#custom_date_range').hide()

  # action triggered when clicking 'update' button
  $(document).onAction 'update-report', (event) ->
    if $("#date_range_select").val() == "Custom" && ($("#start_date_input").data("date-status") != "ok" && $("#end_date_input").data("date-status") != "ok")
      # show notice
    else
      if UsersCreatedModule.getEventsCreated()
        UsersCreatedModule.drawChart()
        UsersCreatedModule.showDataOnReport()
